springdoc:  
  version: "1.0"
  #show-actuator: true
  swagger-ui:
    enabled: true
    path: "/swagger-doc/swagger-ui.html"
  api-docs:
    enabled: true    
    path: "/swagger-doc/v3/api-docs"
  #packagesToScan: io.gitlab.joasdev.openapi.generated.web
  
