server:
  port: 8070
  
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank
      auto-index-creation: true
      
management:
  endpoints:
    web:
      exposure:
        include: mappings
    